<a href="https://colab.research.google.com/github/kaifkh20/d2l/blob/main/d2lch2_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [8]:
# y = 2x^2 where x is a column factor
x = tf.range(4,dtype=tf.float32)
# tensors are immutable whereas variables are mutable thats why its better to use variable
x = tf.Variable(x)
x

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([0., 1., 2., 3.], dtype=float32)>

In [9]:
# y = 2x.x
with tf.GradientTape() as t:
  y = 2*tf.tensordot(x,x,axes=1)

# now the gradient or differentiation
x_grad = t.gradient(y,x)
y , x_grad
# here y = sum[i=1->n](diff(2x(i)^2)))

(<tf.Tensor: shape=(), dtype=float32, numpy=28.0>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 0.,  4.,  8., 12.], dtype=float32)>)

In [10]:
x_grad == 4*x

<tf.Tensor: shape=(4,), dtype=bool, numpy=array([ True,  True,  True,  True])>

In [12]:
# now y = x
with tf.GradientTape() as t:
   y = tf.reduce_sum(x)
t.gradient(y,x)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 1., 1., 1.], dtype=float32)>

In [13]:
# read about backward for non scalar variables 2.5.2
with tf.GradientTape() as t:
    y = x * x
t.gradient(y, x)  # Same as y = tf.reduce_sum(x * x)


<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 2., 4., 6.], dtype=float32)>

In [15]:
# Set persistent=True to preserve the compute graph.
# This lets us run t.gradient more than once

# suppose we want to do z = x*y and y = x*x
# but we want to know the the influence of x directly on z not via y
# we create a aux term u of which we dont want to create a gradient

with tf.GradientTape(persistent=True) as t:
    y = x * x
    u = tf.stop_gradient(y)
    z = u * x

x_grad = t.gradient(z, x)
x_grad == u


<tf.Tensor: shape=(4,), dtype=bool, numpy=array([ True,  True,  True,  True])>