In [4]:
import tensorflow as tf
import os

os.environ['CUDA_VISIBLE_DEVICES'] = '-1'

In [5]:
x = tf.range(12, dtype=tf.float32)
x

<tf.Tensor: shape=(12,), dtype=float32, numpy=
array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
      dtype=float32)>

In [6]:
tf.size(x)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [7]:
x.shape

TensorShape([12])

In [8]:
X = tf.reshape(x,(3,4))
X

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

In [9]:
tf.zeros((1,3,4))


<tf.Tensor: shape=(1, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [10]:
tf.random.normal(shape=[1,2])

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[1.0938138, 0.834767 ]], dtype=float32)>

In [12]:
X_var = tf.Variable(X)
X_var[1,2].assign(1500)
X_var

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[0.0e+00, 1.0e+00, 2.0e+00, 3.0e+00],
       [4.0e+00, 5.0e+00, 1.5e+03, 7.0e+00],
       [8.0e+00, 9.0e+00, 1.0e+01, 1.1e+01]], dtype=float32)>

In [13]:
tf.exp(x)
x

<tf.Tensor: shape=(12,), dtype=float32, numpy=
array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
      dtype=float32)>

In [14]:
tf.exp(X)
X

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

In [16]:
x = tf.constant([1,2,3,4,5])
y = tf.constant([1,2,3,4,5])
x+y,x-y,x*y,x/y,x**y

(<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 2,  4,  6,  8, 10], dtype=int32)>,
 <tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 0, 0, 0, 0], dtype=int32)>,
 <tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25], dtype=int32)>,
 <tf.Tensor: shape=(5,), dtype=float64, numpy=array([1., 1., 1., 1., 1.])>,
 <tf.Tensor: shape=(5,), dtype=int32, numpy=array([   1,    4,   27,  256, 3125], dtype=int32)>)

In [18]:
X = tf.reshape(tf.range(12,dtype=tf.float32),(3,4))
Y = tf.reshape(tf.range(12,24,dtype=tf.float32),(3,4))

tf.concat([X,Y],axis=0)

<tf.Tensor: shape=(6, 4), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.],
       [16., 17., 18., 19.],
       [20., 21., 22., 23.]], dtype=float32)>

In [19]:
tf.concat([X,Y],axis=1)

<tf.Tensor: shape=(3, 8), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3., 12., 13., 14., 15.],
       [ 4.,  5.,  6.,  7., 16., 17., 18., 19.],
       [ 8.,  9., 10., 11., 20., 21., 22., 23.]], dtype=float32)>

In [46]:
# X==Y
X>Y
# X<Y

<tf.Tensor: shape=(3, 4), dtype=bool, numpy=
array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])>

In [21]:
tf.reduce_sum(X)

<tf.Tensor: shape=(), dtype=float32, numpy=66.0>

In [22]:
tf.reduce_sum(Y)

<tf.Tensor: shape=(), dtype=float32, numpy=210.0>

In [24]:
a = tf.reshape(tf.range(3),(3,1))
b = tf.reshape(tf.range(2),(1,2))
a,b

(<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
 array([[0],
        [1],
        [2]], dtype=int32)>,
 <tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[0, 1]], dtype=int32)>)

In [25]:
a + b

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 1],
       [1, 2],
       [2, 3]], dtype=int32)>

In [29]:
Z = tf.Variable(tf.zeros_like(Y))
print('id(Z)',id(Z))
Z.assign(X+Y)
print('id(Z)',id(Z))

id(Z) 124620139061296
id(Z) 124620139061296


In [32]:
@tf.function 
def computation(X,Y):
    Z = tf.zeros_like(Y)
    A = X+Y
    B = A+Y
    C = B+Y
    return C+Y
computation(X,Y)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 48.,  53.,  58.,  63.],
       [ 68.,  73.,  78.,  83.],
       [ 88.,  93.,  98., 103.]], dtype=float32)>

In [36]:
A = X.numpy()
B = tf.constant(A)
type(A),type(B)

(numpy.ndarray, tensorflow.python.framework.ops.EagerTensor)

In [43]:
a = tf.constant([3.5]).numpy()
a, float(a), int(a)

/tmp/ipykernel_4103/3091482262.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  a, float(a), int(a)


(array([3.5], dtype=float32), 3.5, 3)